[project]
name = "catalog-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Denis Vorovskoy", email = "denis.vorovskoy@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.9",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors (PEP8)
    "W",   # pycodestyle warnings
    "F",   # pyflakes (неиспользуемые импорты, переменные)
    "I",   # isort (порядок импортов)
    "N",   # pep8-naming (имена переменных/функций)
    "UP",  # pyupgrade (устаревшие конструкции)
    "B",   # flake8-bugbear (потенциальные баги)
    "SIM", # flake8-simplify (упрощения)
]
ignore = [
    "E501", # длина строки — форматтер сам разберётся
]